#### Consider the below code to answer further questions:

In [2]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list. The variable 'list_' is a Python list, whereas 'array_list' is a NumPy array.

To print the data types of both variables, we can use the built-in type() function in Python:

In [3]:
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

Since the elements of the list_ are of type string, the data type of each element will be str. The elements of the array_list are also string type, but they are represented as numpy.str_.

To print the data type of each element of list_, we can use a for loop and the type() function. To print the data type of each element of array_list, we can use the dtype attribute of NumPy arrays.

In [4]:
for element in list_:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
for element in array_list:
    print(element.dtype)


<U1
<U1
<U1
<U1
<U1


#### Q3. Considering the following changes in the variable, array_list:

In [6]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

In [9]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list")
for element in array_list:
    print(type(element))


Data type of elements in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Consider the below code to answer further questions:

In [11]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [12]:
print("Shape:", num_array.shape)
print("Size:", num_array.size)


Shape: (2, 3)
Size: 6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3)]

In [13]:
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0]

In [14]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
